### ISSUE TITLE
 KaliLinux-NICE-DCV and assignStaticIP issue

### ISSUE THREAD

**Issue by ruzickap** [aws-samples/amazon-ec2-nice-dcv-samples#7]
Hello.

I tried to deploy the latest `KaliLinux-NICE-DCV.yaml` template and go the issue with `assignStaticIP`:

```bash
$ wget https://raw.githubusercontent.com/aws-samples/amazon-ec2-nice-dcv-samples/ce2c1345349d979fe9156b009f00e24f22201230/cfn/KaliLinux-NICE-DCV.yaml

$ rain deploy --yes KaliLinux-NICE-DCV.yaml KaliLinux-NICE-DCV --params assignStaticIP=yes,ec2KeyPair=wordpress-test,vpcID=vpc-026739ec964c7e79e,subnetID=subnet-096568d329a921083,allowWebServerPorts=HTTP-and-HTTPS

error creating changeset: Parameter 'assignStaticIP' must be one of AllowedValues
```

Thanks for looking at it...

**Comment by limmike** [comment]
Hello!

Default value for `assignStaticIP` is `Yes`

> rain deploy --yes ...  --params assignStaticIP=yes ...

CloudFormation is case-sensitive,  use  `Yes` instead of `yes`  


`rain deploy --yes KaliLinux-NICE-DCV.yaml KaliLinux-NICE-DCV --params assignStaticIP=Yes,ec2KeyPair=wordpress-test,vpcID=vpc-026739ec964c7e79e,subnetID=subnet-096568d329a921083,allowWebServerPorts=HTTP-and-HTTPS`

**Comment by ruzickap** [comment]
Thank you for your quick reaction.

It seems line `yes` -> `Yes` didn't help and rain without the `assignStaticIP` doesn't seems to work as well.

It seems like it is a problem of [rain](https://github.com/aws-cloudformation/rain).

Does any of these commands work for you?

```bash
$ rain --version
Rain v1.19.0 darwin/arm64

$ rain deploy --yes KaliLinux-NICE-DCV.yaml KaliLinux-NICE-DCV --params assignStaticIP=Yes,ec2KeyPair=wordpress-test,vpcID=vpc-026739ec964c7e79e,subnetID=subnet-096568d329a921083,allowWebServerPorts=HTTP-and-HTTPS

$ rain deploy --yes KaliLinux-NICE-DCV.yaml KaliLinux-NICE-DCV --params ec2KeyPair=wordpress-test,vpcID=vpc-026739ec964c7e79e,subnetID=subnet-096568d329a921083,allowWebServerPorts=HTTP-and-HTTPS
```

None of these works for me, but I'm able to deploy your CloudFormation template with `aws cloudformation deploy`:

```bash
$ aws cloudformation deploy --capabilities CAPABILITY_IAM --parameter-overrides ec2KeyPair=wordpress-test vpcID=vpc-0aff7a314408ad32b subnetID=subnet-03431286e23f54b8e allowWebServerPorts=HTTP-and-HTTPS --stack-name KaliLinux-NICE-DCV --template-file KaliLinux-NICE-DCV.yaml --s3-bucket my-bucket

Waiting for changeset to be created..
Waiting for stack create/update to complete
Successfully created/updated stack - KaliLinux-NICE-DCV
```

If you agree I would like to close this ticket and open a new one with [rain](https://github.com/aws-cloudformation/rain).

Thank you...

**Comment by limmike** [comment]
Does not work for me either. 

```
% rain --version
Rain v1.19.0 darwin/arm64
% rain deploy --yes KaliLinux-NICE-DCV.yaml KaliLinux-NICE-DCV --params ec2KeyPair=MyKeyPair,vpcID=vpc-632fde01,subnetID=subnet-8d559fc1,allowWebServerPorts=HTTP-and-HTTPS,assignStaticIP=Yes
error creating changeset: Parameter 'assignStaticIP' must be one of AllowedValues
```

Think I know why. 

In my [template](https://github.com/aws-samples/amazon-ec2-nice-dcv-samples/blob/main/cfn/KaliLinux-NICE-DCV.yaml), you will notice that `Yes` and `No` are enclosed in double quotes.
```
  assignStaticIP:
    Type: String
    Description: Associate static public IPv4 address ( https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html )
    AllowedValues:
      - "Yes"
      - "No"
    Default: "Yes"

  allowWebServerPorts:
    Type: String
    Description: Allow HTTP and/or HTTPS inbound
    AllowedValues:
      - "No"
      - HTTP-and-HTTPS
      - HTTP
      - HTTPS
```
If we change the `"Yes"` and `"No"` to `Yes` and `No` and upload to CloudFormation console, the options will appear as `true` and `false`. 

Tried enclosing `Yes` in quotes and double quotes. Still does not work  
```
% rain deploy --yes KaliLinux-NICE-DCV.yaml KaliLinux-NICE-DCV --params ec2KeyPair=MyKeyPair,vpcID=vpc-632fde01,subnetID=subnet-8d559fc1,allowWebServerPorts=HTTP-and-HTTPS,assignStaticIP="Yes"
error creating changeset: Parameter 'assignStaticIP' must be one of AllowedValues
```

Guess rain is interpreting `Yes` as a true/false *boolean* instead of Yes/No *string*

Edit: Found the [solution](https://github.com/aws-cloudformation/rain/issues/316), add `--node-style original`

```
rain deploy --yes KaliLinux-NICE-DCV.yaml KaliLinux-NICE-DCV --params ec2KeyPair=MyKeyPair,vpcID=vpc-632fde01,subnetID=subnet-8d559fc1,allowWebServerPorts=HTTP-and-HTTPS,assignStaticIP="Yes" --node-style original
```




I agree. We can close this ticket

Thanks for the support
